// NOTE: since sub-mods are generated by protoc, rust 2018 style macro does not work.
#[macro_use]
extern crate serde;

pub mod api;
#[allow(unused_variables)]
pub mod api_grpc;

mod Contract;
mod Discover;
mod Tron;

pub mod core {
    pub use super::Contract::*;
    pub use super::Discover::*;
    pub use super::Tron::*;
}
